config/routes.rb
Rails.application.routes.draw do
  root 'cooking_records#index'
  get 'cooking_records', to: 'cooking_records#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cooking_records_controller.rb
require 'net/http'
require 'uri'
require 'json'

class CookingRecordsController < ApplicationController
  RECORDS_PER_PAGE = 6  # 各ページに表示するレコードの数

  def index
    offset = params.fetch(:offset, 0).to_i
    uri = URI.parse("https://cooking-records.ex.oishi-kenko.com/cooking_records")

    uri.query = URI.encode_www_form({ offset: offset, limit: RECORDS_PER_PAGE })

    response = Net::HTTP.get_response(uri)

    @cooking_records = JSON.parse(response.body)['cooking_records']

    @next_offset = offset + RECORDS_PER_PAGE if @cooking_records.length == RECORDS_PER_PAGE
    @prev_offset = [offset - RECORDS_PER_PAGE, 0].max if offset > 0
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooking_records_helper.rb
module CookingRecordsHelper
end

app/views/cooking_records/index.html.erb
<div class="container">
  <h1 class="text-center my-4">料理記録アルバム</h1>
  <div class="row">
    <% @cooking_records.each do |record| %>
      <div class="col-md-4 py-2">
        <div class="card mx-auto" style="width: 18rem;">
          <img src="<%= record['image_url'] %>" class="card-img-top" alt="Record image">
          <div class="card-body">
            <p class="card-text">
              <%= case record['recipe_type']
                  when 'main_dish' then '主菜/主食'
                  when 'side_dish' then '副菜'
                  when 'soup' then 'スープ'
                  else record['recipe_type']
                  end %>
            </p>
            <p class="card-text"><%= record['comment'] %></p>
            <p class="card-text"><%= DateTime.parse(record['recorded_at']).strftime('%Y-%m-%d') %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <nav aria-label="Page navigation example" class="d-flex justify-content-end">
    <ul class="pagination">
      <% if @prev_offset %>
        <li class="page-item">
          <%= link_to cooking_records_path(offset: @prev_offset), class: 'page-link', aria: { label: 'Previous' } do %>
            <span aria-hidden="true">&laquo;</span>
          <% end %>
        </li>
      <% end %>
      <% if @next_offset %>
        <li class="page-item">
          <%= link_to cooking_records_path(offset: @next_offset), class: 'page-link', aria: { label: 'Next' } do %>
            <span aria-hidden="true">&raquo;</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappyCookingRecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>